- platform: bayesian
  prior: 0.6
  name: 'Trent Bayesian Presence'
  probability_threshold: 0.9
  observations:
    - entity_id: 'device_tracker.trent_unifi'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.trent_ios'
      prob_given_true: 0.9
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.trent_owntracks'
      prob_given_true: 0.9
      prob_given_false: 0.4
      platform: 'state'
      to_state: 'home'

- platform: bayesian
  prior: 0.6
  name: 'Ayesha Bayesian Presence'
  probability_threshold: 0.9
  observations:
    - entity_id: 'device_tracker.ayesha_unifi'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.ayesha_ios'
      prob_given_true: 0.9
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.ayesha_owntracks'
      prob_given_true: 0.9
      prob_given_false: 0.4
      platform: 'state'
      to_state: 'home'